<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="35632" started-at="2019-06-17T10:49:16Z" finished-at="2019-06-17T10:49:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="35632" started-at="2019-06-17T10:49:16Z" finished-at="2019-06-17T10:49:52Z">
      <class name="testscripts.LoginTest">
        <test-method status="PASS" signature="reportConfig()[pri:0, instance:testscripts.LoginTest@4abdb505]" name="reportConfig" is-config="true" duration-ms="194" started-at="2019-06-17T10:49:16Z" finished-at="2019-06-17T10:49:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportConfig -->
        <test-method status="PASS" signature="startUp()[pri:0, instance:testscripts.LoginTest@4abdb505]" name="startUp" is-config="true" duration-ms="3741" started-at="2019-06-17T10:49:16Z" finished-at="2019-06-17T10:49:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startUp -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:testscripts.LoginTest@4abdb505]" name="loginTest" duration-ms="28880" started-at="2019-06-17T10:49:20Z" finished-at="2019-06-17T10:49:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="sendSMS(org.testng.ITestResult)[pri:0, instance:testscripts.LoginTest@4abdb505]" name="sendSMS" is-config="true" duration-ms="2937" started-at="2019-06-17T10:49:49Z" finished-at="2019-06-17T10:49:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=SUCCESS method=LoginTest.loginTest()[pri:0, instance:testscripts.LoginTest@4abdb505] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
            <message>
              <![CDATA[Fail to save: an error occurs while saving the package : The part /docProps/core.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.ZipPackagePropertiesMarshaller@69c79f09]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/core.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.ZipPackagePropertiesMarshaller@69c79f09
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:503)
at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1425)
at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:201)
at utility.BaseTest.setExcelData(BaseTest.java:192)
at testscripts.LoginTest.sendSMS(LoginTest.java:204)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/core.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.ZipPackagePropertiesMarshaller@69c79f09
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:486)
... 32 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendSMS -->
        <test-method status="SKIP" signature="getResult(org.testng.ITestResult)[pri:0, instance:testscripts.LoginTest@4abdb505]" name="getResult" is-config="true" duration-ms="0" started-at="2019-06-17T10:49:52Z" finished-at="2019-06-17T10:49:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- testscripts.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
